name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Download cross-compiler
      run: |
        mkdir DEPENDS
        cd DEPENDS
        release=or1k-elf_gcc5.3.0_binutils2.26_newlib2.4.0_gdb7.11.tgz
        wget https://github.com/openrisc/newlib/releases/download/v2.4.0/$release
        tar -xzf $release
        ls
        echo $(pwd)
        cd ..
        
    - name: Check cross-compiler
      run: |
        echo "$(pwd)/DEPENDS/or1k-elf/bin" >> $GITHUB_PATH
        echo $PATH
        or1k-elf-gcc --version
        
    - name: Check cross-compiler (again)
      run: or1k-elf-gcc --version
        
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --verbose
