name: Matrix

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        sanitize: [address,undefined,thread]
        
    name: ${{matrix.sanitize}}
        
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Build
      run: echo $CXX_FLAGS
      env:
        CXX_FLAGS: -fsanitize=${{matrix.sanitize}}
