name: Matrix

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        version: [1.2a, 2.0, 3.1, 4.4]
        
    name: Build - Version ${{matrix.version}}
        
    env:
      VERSION: v${{matrix.version}}

    steps:
    - name: Setup
      run: sudo apt-get install libelf-dev libvncserver-dev

    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Echo ${{matrix.version}}
      run: echo ${{env.VERSION}}
